/*
  * Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *  http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
*/
import { removeExtraIndentation } from '../../utils/formatting'

export function createCommentaryString() {
  const commentary = `
    /**
     * BEAGLE-ANGULAR
     *
     * Please, do not change this file.
     *
     * This file has been automatically generated by the lib beagle-angular. This is necessary when
     * the project uses ViewEngine instead of Ivy.
     *
     * This file should be regenerated every time a component in your beagle configuration is added,
     * removed or its inputs are changed. To regenerate it, run:
     * yarn beagle view-engine
     **/
  `

  return removeExtraIndentation(commentary, 4)
}
