/* 
 * Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

import { removeExtraIndentation } from '../../utils/formatting'

export function createCommentaryString() {
  const commentary = `
    /**
     * BEAGLE-ANGULAR
     *
     * Please, do not change this file.
     *
     * This file has been automatically generated by the lib beagle-angular. This is necessary when
     * the project uses ViewEngine instead of Ivy.
     *
     * This file should be regenerated every time a component in your beagle configuration is added,
     * removed or its inputs are changed. To regenerate it, run:
     * yarn beagle view-engine
     **/
  `

  return removeExtraIndentation(commentary, 4)
}
