#
  # Copyright 2020, 2022 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #  http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
#

name: Pull request validation

on:
  pull_request:
    branches: [ development, main, release/* ]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - name: clear cache
      run: yarn cache clean

    # Checks-out beagle-web-core under $GITHUB_WORKSPACE
    - name: clone beagle-web-core
      uses: actions/checkout@v2
      with:
        repository: ZupIT/beagle-web-core
        path: core

    - name: install beagle-web-core
      run: cd core && yarn

    - name: build beagle-web-core
      run: cd core && yarn build

    - name: create link for beagle-web-core
      run: cd core/dist && yarn link

    # Checks-out beagle-angular under $GITHUB_WORKSPACE
    - name: clone beagle-angular
      uses: actions/checkout@v2
      with:
        path: angular

    - name: link beagle-angular to beagle-web-core
      run: cd angular && yarn link @zup-it/beagle-web

    - name: install
      run: cd angular && yarn
    
    - name: lint
      run: cd angular && yarn lint

    - name: test
      run: cd angular && yarn test

    - name: test and comment
      continue-on-error: true
      uses: mattallty/jest-github-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        working-directory: "angular"
        test-command: "yarn test --maxWorkers=2"
    
    - name: build
      run: cd angular && yarn build
